# config.yaml
path: C:/Users/hp/OneDrive/Documents/segmentationdataset/image-segmentation-yolov8/images
train: C:/Users/hp/OneDrive/Documents/segmentationdataset/image-segmentation-yolov8/images/train
val: C:/Users/hp/OneDrive/Documents/segmentationdataset/image-segmentation-yolov8/images/val

nc: 5  # Number of classes
names: ['inflorescence', 'old inflorescence', 'young inflorescence', 'arecanut', 'arecanut tree']

